spring.application.name=trabalhoIndividual

spring.datasource.url=jdbc:postgresql://localhost:5432/cliente
spring.datasource.username=postgres
spring.datasource.password=201012


spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.generate.ddl=true